project: 
  type: website
  
website: 
  page-navigation: true
  title: "Our onboarding guide" 
  site-url: "https://openscapes.github.io/series" # change

 
  repo-url: https://github.com/openscapes/series # change
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Our team, 2022"
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.md
      - culture-philosophy.md
      - code-of-conduct.md
      - onboarding.md
      - expectations.md
      - computing.md
      - offboarding.md

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
