project: 
  type: website
  
website: 
  page-navigation: true
  title: "Making sharable documents with Quarto" 
  site-url: "https://dfe-analytical-services.github.io/stats-production-guidance-quarto/" 
  repo-url: https://github.com/dfe-analytical-services/stats-production-guidance-quarto 
  repo-actions: [issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By DfE, 2023"
    
  sidebar:
    logo: "images/duck_guidance.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://explore-education-statistics.service.gov.uk/
        text: "Explore Education Statistics"
      - icon: github
        href: https://github.com/dfe-analytical-services
        text: "DfE Analytical Services"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: learning-development/learning-development.qmd
        contents:
          - learning-development/sql.qmd
          - learning-development/r.qmd
          - learning-development/git.qmd
      - section: "Creating statistics"
        contents: 
          - creating-statistics/ud.qmd
          - creating-statistics/cd.qmd
      - section: "Publishing statistics"
        contents: 
          - publishing-statistics/pub.qmd
          - publishing-statistics/ees.qmd
          - publishing-statistics/examples.qmd
          - publishing-statistics/dashboards.qmd
          - publishing-statistics/embedded-charts.qmd
      - section: "Understanding users"
        contents: 
          - understanding-users/user-eng.qmd
          - understanding-users/user-analytics.qmd
      - section: "Reproducible Analytical Pipelines (RAP)"
        contents: 
          - RAP/rap.qmd
          - RAP/rap-managers.qmd
          - RAP/rap-faq.qmd

format:
  html:
    theme:
      light: flatly # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
